import type { ParentDashboardData } from "../types/dashboard.types";

// Mock data for parent dashboard - NO API CALLS until endpoints provided
export const mockParentDashboardData: ParentDashboardData = {
	selectedChild: {
		id: "1",
		name: "Jane Doe",
		avatar: "👧",
		class: "JSS1",
		classArm: "A",
	},
	children: [
		{
			id: "1",
			name: "Jane Doe",
			avatar: "👧",
			class: "JSS1",
			classArm: "A",
		},
		{
			id: "2",
			name: "James Doe",
			avatar: "👦",
			class: "JSS2",
			classArm: "B",
		},
		{
			id: "3",
			name: "Grace Doe",
			avatar: "👧",
			class: "JSS3",
			classArm: "C",
		},
	],
	overview: {
		attendance: {
			percentage: 54,
			totalClasses: 20,
			attended: 11,
			missed: 9,
		},
		assignments: {
			total: 5,
			completed: 2,
			pending: 3,
		},
		tests: {
			averageScore: 54,
			totalTests: 2,
			completedTests: 2,
			pendingTests: 0,
		},
	},
	recentClasses: [
		{
			id: "1",
			subjectName: "Biology",
			subjectIcon: "🔬",
			progress: 58,
			lessonNumber: 9,
			totalLessons: 16,
			lastAccessed: "10 mins ago",
			color: "bg-green-100",
		},
		{
			id: "2",
			subjectName: "Further Maths",
			subjectIcon: "🧮",
			progress: 58,
			lessonNumber: 9,
			totalLessons: 16,
			lastAccessed: "10 mins ago",
			color: "bg-red-100",
		},
		{
			id: "3",
			subjectName: "Physics",
			subjectIcon: "💡",
			progress: 58,
			lessonNumber: 9,
			totalLessons: 16,
			lastAccessed: "45 mins ago",
			color: "bg-teal-100",
		},
	],
	events: [
		{
			id: "1",
			title: "Children's Day",
			description:
				"Further details would be announced soon as we get more information. Trust us.",
			date: "2025-05-27",
			day: 27,
			month: "May",
			type: "school",
		},
		{
			id: "2",
			title: "Open Day",
			description: "Further details would be announced soon",
			date: "2025-05-30",
			day: 30,
			month: "May",
			type: "school",
		},
		{
			id: "3",
			title: "Colour Friday",
			description: "Further details would be announced soon",
			date: "2025-05-03",
			day: 3,
			month: "May",
			type: "school",
		},
		{
			id: "4",
			title: "Open Day",
			description:
				"Further details would be announced soon as we get more information. Trust us.",
			date: "2025-05-30",
			day: 30,
			month: "May",
			type: "school",
		},
		{
			id: "5",
			title: "Open Day",
			description: "Further details would be announced soon",
			date: "2025-05-30",
			day: 30,
			month: "May",
			type: "school",
		},
	],
	upcomingDeadline: {
		subject: "Physics",
		dueIn: "2hrs 30mins",
		dueDate: new Date(Date.now() + 2.5 * 60 * 60 * 1000),
	},
};
