import type { ChildSubject, SubjectDetail } from "../types/child.types";

// Mock subjects data for child
export const mockChildSubjects: ChildSubject[] = [
	{
		id: "1",
		name: "Biology",
		icon: "🔬",
		teacher: "Teacher: Andrew Hines",
		lessonNumber: 9,
		totalLessons: 16,
		progress: 58,
		color: "bg-green-100",
	},
	{
		id: "2",
		name: "Further Mathematics",
		icon: "🧮",
		teacher: "Teacher: Andrew Hines",
		lessonNumber: 9,
		totalLessons: 16,
		progress: 58,
		color: "bg-red-100",
	},
	{
		id: "3",
		name: "English",
		icon: "📚",
		teacher: "Teacher: Andrew Hines",
		lessonNumber: 9,
		totalLessons: 16,
		progress: 58,
		color: "bg-blue-100",
	},
	{
		id: "4",
		name: "Chemistry",
		icon: "🧪",
		teacher: "Teacher: Andrew Hines",
		lessonNumber: 9,
		totalLessons: 16,
		progress: 58,
		color: "bg-purple-100",
	},
	{
		id: "5",
		name: "Economics",
		icon: "💰",
		teacher: "Teacher: Andrew Hines",
		lessonNumber: 9,
		totalLessons: 16,
		progress: 58,
		color: "bg-teal-100",
	},
	{
		id: "6",
		name: "Geography",
		icon: "🌍",
		teacher: "Teacher: Andrew Hines",
		lessonNumber: 9,
		totalLessons: 16,
		progress: 58,
		color: "bg-lime-100",
	},
	{
		id: "7",
		name: "Civic Education",
		icon: "🏛️",
		teacher: "Teacher: Andrew Hines",
		lessonNumber: 9,
		totalLessons: 16,
		progress: 58,
		color: "bg-amber-100",
	},
	{
		id: "8",
		name: "Mathematics",
		icon: "🔢",
		teacher: "Teacher: Andrew Hines",
		lessonNumber: 9,
		totalLessons: 16,
		progress: 58,
		color: "bg-orange-100",
	},
	{
		id: "9",
		name: "Computer Science",
		icon: "💻",
		teacher: "Teacher: Andrew Hines",
		lessonNumber: 9,
		totalLessons: 16,
		progress: 58,
		color: "bg-rose-100",
	},
	{
		id: "10",
		name: "Agriculture",
		icon: "🌾",
		teacher: "Teacher: Andrew Hines",
		lessonNumber: 9,
		totalLessons: 16,
		progress: 58,
		color: "bg-green-50",
	},
	{
		id: "11",
		name: "History",
		icon: "📜",
		teacher: "Teacher: Andrew Hines",
		lessonNumber: 9,
		totalLessons: 16,
		progress: 58,
		color: "bg-yellow-100",
	},
	{
		id: "12",
		name: "Food and Nutrition",
		icon: "🍎",
		teacher: "Teacher: Andrew Hines",
		lessonNumber: 9,
		totalLessons: 16,
		progress: 58,
		color: "bg-pink-100",
	},
];

// Mock subject detail data
export const mockSubjectDetails: Record<string, SubjectDetail> = {
	"1": {
		id: "1",
		name: "Biology",
		icon: "🔬",
		description:
			"Explore the fascinating world of living organisms. From microscopic cells to complex ecosystems, dive into the science of life, evolution, and the interconnectedness of all living things.",
		teacher: "Andrew Hines",
		progress: 58,
		color: "bg-green-100",
		lessons: [
			{ id: "1", number: 1, title: "Introduction", status: "completed" },
			{
				id: "2",
				number: 2,
				title: "Reproduction in Organisms",
				status: "in_progress",
			},
			{ id: "3", number: 3, title: "Reproduction in Organisms", status: "locked" },
			{ id: "4", number: 4, title: "Introduction", status: "locked" },
			{ id: "5", number: 5, title: "Introduction", status: "locked" },
			{ id: "6", number: 6, title: "Introduction", status: "locked" },
			{ id: "7", number: 7, title: "Introduction", status: "locked" },
			{ id: "8", number: 8, title: "Introduction", status: "locked" },
			{ id: "9", number: 9, title: "Introduction", status: "locked" },
			{ id: "10", number: 10, title: "Introduction", status: "locked" },
		],
	},
};
// Mock lesson content
